### ISSUE TITLE
Not all possible words are generated for more complex word structure rules.

### ISSUE THREAD

**Issue by ahewlett** [ahewlett/VocableParser#1]
For example, given the word structure rule: 
> (V)VC(V)

The following subsets should be generated to create words:
> VC
> (V)VC
> (V)VC(V)
> VC(V) --> This subset is **not** generated.

**Comment by p59crw** [comment]
Upon further testing, it seems any structure with two or more optional characters AND a single root character omits the final character in permutations, even if it acknowledges the permutation as a possibility. Two-character roots will work if optional characters are to the left in initial position, but will fail with optional characters in final position.

For example, (C)(C)CV shows all possible permutations correctly as (C)(C)CV, (C)CV, and CV, and outputs all permutations correctly.

However, (C)(C)C, outputs the permutations correctly as (C)(C)C, (C)C, and C, but it fails to output the permutations of C in the word list.

(C)C(V), for example, like the OP issue, outputs (C)C(V), (C)C, and C, but not C(V).

**Comment by ahewlett** [comment]
Commit b5a0dde should fix the issue where single components were not getting added to the generated word list. I'm still investigating a solution for my original issue.

**Comment by p59crw** [comment]
Can confirm that commit [b5a0dde](https://github.com/ahewlett/VocableParser/commit/b5a0dded58bf61bf06c485fff867e6eb2e46e3e0) does allow single components to be output in the permutation list.

**Comment by ahewlett** [comment]
Closing this issue as it looks like 169f588 corrected it.
